apiVersion: v1
kind: Service
metadata:
  name: nodewebapp-service
spec:
  selector:
    tier: frontend
  clusterIP: 34.118.224.220
  externalTrafficPolicy: Cluster
  ports:
  - name: myport
    port: 8037
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer